server:
  port: 18005
# 数据源配置
spring:
  # datasoure默认使用JDBC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '123456'
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/zipkin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  sleuth:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    password: 
    username: 

zipkin:
  storage:
    type: mysql

logging:
  file: logs/localhost.log